name: Build Raspibian arm64 Binary

on: [workflow_dispatch]

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release

jobs:
    build_raspios_bullseye_arm64:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2

        - name: Create Build Environment
          run: rm -rf ${{runner.workspace}}/build && cmake -E make_directory ${{runner.workspace}}/build
        
        - name: Prepare CMake
          working-directory: ${{runner.workspace}}/build
          run: cmake $GITHUB_WORKSPACE -DOPT_BUILD_BLADERF_SOURCE=ON -DOPT_BUILD_LIMESDR_SOURCE=ON -DOPT_BUILD_SDRPLAY_SOURCE=ON -DOPT_BUILD_NEW_PORTAUDIO_SINK=ON -DOPT_BUILD_M17_DECODER=ON

        - name: Build
          working-directory: ${{runner.workspace}}/build
          run: make VERBOSE=1 -j3

        - name: Create Dev Archive
          working-directory: ${{runner.workspace}}
          run: sh $GITHUB_WORKSPACE/make_debian_package.sh ./build 'libfftw3-dev, libglfw3-dev, libvolk2-dev, librtaudio-dev' && mv sdrpp_debian_amd64.deb sdrpp_debian_armhf.deb
        
        - name: Save Deb Archive
          uses: actions/upload-artifact@v2
          with:
              name: sdrpp_raspios_bullseye_armhf
              path: ${{runner.workspace}}/sdrpp_debian_armhf.deb
